title: Applying ML Techniques to Identify Cancer Types
description: Classify and predict cancer types based on gene expression levels
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman